export const themeConfig: Record<string, any> = {
    violet: {
        text: 'text-violet-600',
        textLight: 'text-violet-400',
        textDark: 'text-violet-900',
        bg: 'bg-violet-600',
        bgHover: 'hover:bg-violet-600',
        bgLight: 'bg-violet-100',
        bgSoft: 'bg-violet-50',
        border: 'border-violet-200',
        from: 'from-violet-600',
        via: 'via-violet-500',
        decoration: 'decoration-violet-500',
        shadow: 'shadow-violet-500/20',
        ring: 'focus:ring-violet-500',
        selection: 'selection:bg-violet-200 selection:text-violet-900',
        stroke: 'stroke-violet-600',
        fromOp10: 'from-violet-600/10',
        textLightOp10: 'text-violet-400/10',
    },
    blue: {
        text: 'text-blue-600',
        textLight: 'text-blue-400',
        textDark: 'text-blue-900',
        bg: 'bg-blue-600',
        bgHover: 'hover:bg-blue-600',
        bgLight: 'bg-blue-100',
        bgSoft: 'bg-blue-50',
        border: 'border-blue-200',
        from: 'from-blue-600',
        via: 'via-blue-500',
        decoration: 'decoration-blue-500',
        shadow: 'shadow-blue-500/20',
        ring: 'focus:ring-blue-500',
        selection: 'selection:bg-blue-200 selection:text-blue-900',
        stroke: 'stroke-blue-600',
        fromOp10: 'from-blue-600/10',
        textLightOp10: 'text-blue-400/10',
    },
    emerald: {
        text: 'text-emerald-600',
        textLight: 'text-emerald-400',
        textDark: 'text-emerald-900',
        bg: 'bg-emerald-600',
        bgHover: 'hover:bg-emerald-600',
        bgLight: 'bg-emerald-100',
        bgSoft: 'bg-emerald-50',
        border: 'border-emerald-200',
        from: 'from-emerald-600',
        via: 'via-emerald-500',
        decoration: 'decoration-emerald-500',
        shadow: 'shadow-emerald-500/20',
        ring: 'focus:ring-emerald-500',
        selection: 'selection:bg-emerald-200 selection:text-emerald-900',
        stroke: 'stroke-emerald-600',
        fromOp10: 'from-emerald-600/10',
        textLightOp10: 'text-emerald-400/10',
    },
    rose: {
        text: 'text-rose-600',
        textLight: 'text-rose-400',
        textDark: 'text-rose-900',
        bg: 'bg-rose-600',
        bgHover: 'hover:bg-rose-600',
        bgLight: 'bg-rose-100',
        bgSoft: 'bg-rose-50',
        border: 'border-rose-200',
        from: 'from-rose-600',
        via: 'via-rose-500',
        decoration: 'decoration-rose-500',
        shadow: 'shadow-rose-500/20',
        ring: 'focus:ring-rose-500',
        selection: 'selection:bg-rose-200 selection:text-rose-900',
        stroke: 'stroke-rose-600',
        fromOp10: 'from-rose-600/10',
        textLightOp10: 'text-rose-400/10',
    },
    amber: {
        text: 'text-amber-600',
        textLight: 'text-amber-400',
        textDark: 'text-amber-900',
        bg: 'bg-amber-600',
        bgHover: 'hover:bg-amber-600',
        bgLight: 'bg-amber-100',
        bgSoft: 'bg-amber-50',
        border: 'border-amber-200',
        from: 'from-amber-600',
        via: 'via-amber-500',
        decoration: 'decoration-amber-500',
        shadow: 'shadow-amber-500/20',
        ring: 'focus:ring-amber-500',
        selection: 'selection:bg-amber-200 selection:text-amber-900',
        stroke: 'stroke-amber-600',
        fromOp10: 'from-amber-600/10',
        textLightOp10: 'text-amber-400/10',
    },
    cyan: {
        text: 'text-cyan-600',
        textLight: 'text-cyan-400',
        textDark: 'text-cyan-900',
        bg: 'bg-cyan-600',
        bgHover: 'hover:bg-cyan-600',
        bgLight: 'bg-cyan-100',
        bgSoft: 'bg-cyan-50',
        border: 'border-cyan-200',
        from: 'from-cyan-600',
        via: 'via-cyan-500',
        decoration: 'decoration-cyan-500',
        shadow: 'shadow-cyan-500/20',
        ring: 'focus:ring-cyan-500',
        selection: 'selection:bg-cyan-200 selection:text-cyan-900',
        stroke: 'stroke-cyan-600',
        fromOp10: 'from-cyan-600/10',
        textLightOp10: 'text-cyan-400/10',
    },
};
